# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *" #Makes sense, we are testing against master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Zig
        # You may pin to the exact commit or the version.
        # uses: goto-bus-stop/setup-zig@41ae19e72e21b9a1380e86ff9f058db709fc8fc6
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.1

      - run: zig version
      - run: zig env

      - name: Debug Build
        run: zig build

      - name: Release Build
        run: zig build -Drelease-fast

      - name: Bench
        run: ./zig-out/bin/Avalanche bench

      - name: Build artifacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          chmod +x build_all.sh
          ./build_all.sh
      - name: Upload artifacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: artifacts/*.zip
